import localFont from 'next/font/local'
const SuisseIntl = localFont({ src: '../fonts/SuisseIntl-Regular.woff' })

import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SuisseIntl.className}>{children}</body>
    </html>
  );
}
